const dictionaries = {
  th: {
    'Free access': 'เข้าใช้ได้ฟรี',
    'Access 1 time': 'เข้าใช้ได้ 1 ครั้ง',
    'Unlimited access': 'เข้าใช้ได้ไม่จำกัด',
    'Access {count} times': 'เข้าใช้ได้ {count} ครั้ง',
    'Unspecified branch': 'ยังไม่ระบุสาขา',
    'Unspecified instructor': 'ยังไม่ระบุผู้สอน',
    Course: 'คอร์ส',
    Session: 'รอบเรียน',
    'Hand-picked experiences by our studio team': 'ประสบการณ์คัดสรรโดยทีมสตูดิโอ',
    'Register for free': 'ลงทะเบียนฟรี',
    'Book this course': 'จองคอร์สนี้',
    'Featured courses': 'คอร์สแนะนำ',
    'Curated classes with real-time availability': 'คัดสรรคอร์สพร้อมเช็กที่นั่งแบบเรียลไทม์',
    'View all': 'ดูทั้งหมด',
    'Loading courses...': 'กำลังโหลดคอร์ส...',
    'Unable to load courses right now': 'ไม่สามารถโหลดคอร์สตอนนี้',
    'No courses are open for booking yet': 'ยังไม่มีคอร์สเปิดให้จอง',
    'Omise Payment': 'ชำระเงินผ่าน Omise',
    'Hybrid / Onsite / Online': 'ไฮบริด / ที่สตูดิโอ / ออนไลน์',
    'Seamless booking and payments with Omise and shared SchemaDB — works with LINE LIFF login and real-time access control.':
      'จองและชำระเงินง่ายด้วย Omise และ SchemaDB ร่วมกับ LIFF ตรวจสอบสิทธิ์แบบเรียลไทม์.',
    'Start browsing': 'เริ่มเลือกคอร์ส',
    'Premium courses': 'คอร์สพรีเมียม',
    'SIGNATURE EXPERIENCE': 'ประสบการณ์ซิกเนเจอร์',
    'Find the right course': 'หาคอร์สที่เหมาะกับคุณ',
    'All courses': 'คอร์สทั้งหมด',
    'Search and filter by branch and instructor': 'ค้นหาและกรองตามสาขาและผู้สอน',
    'Loading all courses...': 'กำลังโหลดคอร์สทั้งหมด...',
    'Unable to fetch courses': 'ไม่สามารถดึงข้อมูลคอร์ส',
    'No courses match your search': 'ไม่พบคอร์สที่ตรงกับการค้นหา',
    'Seats {count}': 'ที่นั่ง {count}',
    'Check availability': 'ตรวจสอบจำนวนที่นั่ง',
    'Studio instructor': 'ผู้สอนประจำสตูดิโอ',
    'View details': 'ดูรายละเอียด',
    Register: 'ลงทะเบียน',
    'Buy course': 'ซื้อคอร์ส',
    'Search course name or keywords': 'ค้นหาชื่อคอร์สหรือคีย์เวิร์ด',
    'Try Yin, Mobility, Meditation': 'ลองใส่คำว่า Yin, Mobility, Meditation',
    'Branch / Location': 'สาขา / สถานที่',
    'All locations': 'ทุกสาขา',
    Instructor: 'ผู้สอน',
    'All instructors': 'ผู้สอนทั้งหมด',
    'Loading course details...': 'กำลังโหลดรายละเอียดคอร์ส...',
    'Course not found, please return to the main page': 'ไม่พบคอร์ส กรุณากลับไปหน้าหลัก',
    '← Back': '← กลับ',
    'Price / Access': 'ราคา / สิทธิ์การเข้า',
    'Browse other courses': 'ดูคอร์สอื่น',
    'Register now': 'ลงทะเบียนตอนนี้',
    'Pay via Omise': 'ชำระผ่าน Omise',
    Level: 'ระดับ',
    'Seats left {left}/{capacity}': 'ที่นั่งคงเหลือ {left}/{capacity}',
    Sessions: 'ตารางรอบเรียน',
    'Responsive timetable for Onsite / Online / Hybrid': 'ตารางเรียนสำหรับ Onsite / Online / Hybrid',
    'No sessions available yet': 'ยังไม่มีรอบเรียน',
    '{count} seats left': 'เหลือที่นั่ง {count}',
    'Open for booking': 'เปิดให้จอง',
    Language: 'ภาษา',
  },
  zh: {
    'Free access': '免费使用',
    'Access 1 time': '可使用1次',
    'Unlimited access': '不限次数',
    'Access {count} times': '可使用{count}次',
    'Unspecified branch': '未指定分店',
    'Unspecified instructor': '未指定教练',
    Course: '课程',
    Session: '课次',
    'Hand-picked experiences by our studio team': '由工作室团队精心挑选的体验',
    'Register for free': '免费注册',
    'Book this course': '预订此课程',
    'Featured courses': '精选课程',
    'Curated classes with real-time availability': '精选课程，实时显示席位',
    'View all': '查看全部',
    'Loading courses...': '正在加载课程...',
    'Unable to load courses right now': '目前无法加载课程',
    'No courses are open for booking yet': '尚无课程开放预订',
    'Omise Payment': 'Omise 支付',
    'Hybrid / Onsite / Online': '混合 / 现场 / 在线',
    'Seamless booking and payments with Omise and shared SchemaDB — works with LINE LIFF login and real-time access control.':
      '通过 Omise 与共享 SchemaDB 无缝预订与支付，支持 LINE LIFF 登录与实时权限控制。',
    'Start browsing': '开始浏览',
    'Premium courses': '高级课程',
    'SIGNATURE EXPERIENCE': '特色体验',
    'Find the right course': '找到适合你的课程',
    'All courses': '全部课程',
    'Search and filter by branch and instructor': '按分店与教练搜索和筛选',
    'Loading all courses...': '正在加载全部课程...',
    'Unable to fetch courses': '无法获取课程',
    'No courses match your search': '没有符合搜索的课程',
    'Seats {count}': '席位 {count}',
    'Check availability': '查看空位',
    'Studio instructor': '工作室教练',
    'View details': '查看详情',
    Register: '报名',
    'Buy course': '购买课程',
    'Search course name or keywords': '搜索课程名称或关键词',
    'Try Yin, Mobility, Meditation': '试试输入 Yin、Mobility、Meditation',
    'Branch / Location': '分店 / 地点',
    'All locations': '所有地点',
    Instructor: '教练',
    'All instructors': '所有教练',
    'Loading course details...': '正在加载课程详情...',
    'Course not found, please return to the main page': '未找到课程，请返回主页',
    '← Back': '← 返回',
    'Price / Access': '价格 / 权限',
    'Browse other courses': '浏览其他课程',
    'Register now': '立即报名',
    'Pay via Omise': '使用 Omise 支付',
    Level: '难度',
    'Seats left {left}/{capacity}': '剩余席位 {left}/{capacity}',
    Sessions: '课表',
    'Responsive timetable for Onsite / Online / Hybrid': '适用于现场 / 在线 / 混合的灵活课表',
    'No sessions available yet': '暂时没有课次',
    '{count} seats left': '剩余 {count} 席',
    'Open for booking': '开放预订',
    Language: '语言',
  },
};

export function translateText(text, targetLanguage) {
  const normalized = typeof text === 'string' ? text.trim() : '';
  if (!normalized) return '';
  const dictionary = dictionaries[targetLanguage];
  if (!dictionary) return text;
  return dictionary[normalized] ?? text;
}
